# Generated by Django 5.2.8 on 2025-12-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="text",
            field=models.TextField(default="Blog entry..."),
        ),
    ]
